<a href="https://colab.research.google.com/github/DurgeshKShukla/DurgeshKShukla/blob/main/pandas_Chipotle_project2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
a = pd.read_csv("chipotle.tsv", delimiter='\t')

1. Missing Values:
Question: Check for missing values in each column (Order ID, Quantity, Item Name, Choice Description, Item Price). How should missing values be handled?

In [ ]:
a

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [ ]:
a.isnull().sum()

order_id                 0
quantity                 0
item_name                0
choice_description    1246
item_price               0
dtype: int64

In [ ]:
##Assuming you want to replace NaN in 'choice_description' with 'No Additional Choices'
a['choice_description'].fillna('No Additional Choices', inplace=True)

In [ ]:
print(a)

      order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa
1            1         1                                   Izze
2            1         1                       Nantucket Nectar
3            1         1  Chips and Tomatillo-Green Chili Salsa
4            2         2                           Chicken Bowl
...        ...       ...                                    ...
4617      1833         1                          Steak Burrito
4618      1833         1                          Steak Burrito
4619      1834         1                     Chicken Salad Bowl
4620      1834         1                     Chicken Salad Bowl
4621      1834         1                     Chicken Salad Bowl

                                     choice_description item_price
0                                 No Additional Choices     $2.39
1                                          [Clementine]     $3.39
2                                               [Apple]     $3.39
3                                 No Additional Choices     $2.39
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98
...                                                 ...        ...
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75

[4622 rows x 5 columns]

2. Data Types:
Question: Verify the data types of each column. Do they align with their expected types, and should any adjustments be made?

In [ ]:
# Display the data types of each column
print(a.dtypes)

order_id               int64
quantity               int64
item_name             object
choice_description    object
item_price            object
dtype: object

In [ ]:
# Convert 'item_price' to float or Decimal
a['item_price'] = a['item_price'].replace('[\$,]', '', regex=True).astype(float)

# Display the DataFrame after adjusting data types
print(a)

      order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa
1            1         1                                   Izze
2            1         1                       Nantucket Nectar
3            1         1  Chips and Tomatillo-Green Chili Salsa
4            2         2                           Chicken Bowl
...        ...       ...                                    ...
4617      1833         1                          Steak Burrito
4618      1833         1                          Steak Burrito
4619      1834         1                     Chicken Salad Bowl
4620      1834         1                     Chicken Salad Bowl
4621      1834         1                     Chicken Salad Bowl

                                     choice_description  item_price
0                                                   NaN        2.39
1                                          [Clementine]        3.39
2                                               [Apple]        3.39
3                                                   NaN        2.39
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...       16.98
...                                                 ...         ...
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...       11.75
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...       11.75
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...       11.25
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...        8.75
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...        8.75

[4622 rows x 5 columns]

3. Duplicated Entries:
Question: Identify and handle duplicated entries in the dataset. How might duplicates impact analysis, and what is the appropriate action?

In [ ]:
# Check for duplicated entries in the entire DataFrame
duplicates = a.duplicated()

# Display duplicated entries
print("Duplicated Entries:")
print(a[duplicates])

# Drop duplicated entries
a.drop_duplicates(inplace=True)

# Display the DataFrame after handling duplicates
print("\nDataFrame after handling duplicates:")
print(a)

Duplicated Entries:
      order_id  quantity                            item_name  \
238        103         1                        Steak Burrito
248        108         1                          Canned Soda
297        129         1                        Steak Burrito
381        165         1                    Canned Soft Drink
484        205         1                         Chicken Bowl
567        233         1                    Canned Soft Drink
617        254         1                                Chips
684        282         1                    Canned Soft Drink
773        319         1                         Chicken Bowl
908        376         1                        Steak Burrito
924        381         1                   Chicken Soft Tacos
1003       412         1                        Bottled Water
1117       462         1                      Chicken Burrito
1203       491         1                      Chicken Burrito
1245       507         1                    Canned Soft Drink
1381       561         1                    Canned Soft Drink
1410       573         1                        Bottled Water
1420       576         1                        Barbacoa Bowl
1421       576         1                  Barbacoa Salad Bowl
1502       610         1                      Chicken Burrito
1534       624         1  Chips and Tomatillo-Red Chili Salsa
1548       628         1                  Chips and Guacamole
1612       651         1                                 Izze
1791       724         1                    Canned Soft Drink
1792       724         1                    Canned Soft Drink
2078       838         1                   Chicken Soft Tacos
2127       856         1                      Chicken Burrito
2307       926         1                         Chicken Bowl
2318       926         1                         Chicken Bowl
2362       940         1                    Canned Soft Drink
2448       972         1                         Chicken Bowl
2553      1011         1                    Canned Soft Drink
2554      1011         1                    Canned Soft Drink
2560      1013         1                  Chips and Guacamole
2576      1020         1  Chips and Tomatillo Red Chili Salsa
2662      1057         1                   Chicken Soft Tacos
2708      1074         1                                Chips
2717      1078         1                         Chicken Bowl
2833      1125         1                      Chicken Burrito
2881      1144         1                        Bottled Water
2973      1182         1                         Chicken Bowl
2977      1184         1                           Steak Bowl
3121      1244         1                  Chips and Guacamole
3430      1377         1  Chips and Tomatillo Red Chili Salsa
3637      1454         1                   Chicken Soft Tacos
3716      1484         1                          Canned Soda
3764      1507         1                      Chicken Burrito
3829      1534         1                      Chicken Burrito
3924      1574         1                        Bottled Water
4112      1647         1                         Chicken Bowl
4155      1660         1                  Chips and Guacamole
4236      1691         1                         Chicken Bowl
4266      1701         1                                Chips
4372      1745         1                  Chips and Guacamole
4463      1778         1                    Canned Soft Drink
4479      1785         1                        Bottled Water
4544      1806         1                        Bottled Water
4570      1817         1                        Bottled Water
4603      1827         1                     Barbacoa Burrito

                                     choice_description  item_price
238   [Tomatillo Red Chili Salsa, [Rice, Black Beans...       11.75
248                                      [Mountain Dew]        1.09
297   [Tomatillo Green Chili Salsa, [Rice, Cheese, G...       11.75
381                                              [Coke]        1.25
484   [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...        8.75
567                                         [Diet Coke]        1.25
617                                                 NaN        2.15
684                                              [Coke]        1.25
773   [Tomatillo-Green Chili Salsa (Medium), Black B...        8.49
908   [Roasted Chili Corn Salsa (Medium), [Rice, Faj...        8.99
924           [Tomatillo-Red Chili Salsa (Hot), Cheese]        8.49
1003                                                NaN        1.50
1117  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...       11.25
1203  [Fresh Tomato Salsa, [Cheese, Sour Cream, Lett...        8.75
1245                                         [Lemonade]        1.25
1381                                             [Coke]        1.25
1410                                                NaN        1.50
1420                         [Roasted Chili Corn Salsa]        9.25
1421                         [Roasted Chili Corn Salsa]        9.39
1502  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...        8.75
1534                                                NaN        2.39
1548                                                NaN        4.45
1612                                       [Blackberry]        3.39
1791                                             [Coke]        1.25
1792                                             [Coke]        1.25
2078  [Fresh Tomato Salsa, [Cheese, Sour Cream, Lett...        8.75
2127  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...       11.25
2307  [Roasted Chili Corn Salsa, [Fajita Vegetables,...        8.75
2318  [Roasted Chili Corn Salsa, [Fajita Vegetables,...        8.75
2362                                             [Coke]        1.25
2448  [Tomatillo Red Chili Salsa, [Rice, Black Beans...        8.75
2553                                             [Coke]        1.25
2554                                             [Coke]        1.25
2560                                                NaN        4.45
2576                                                NaN        2.95
2662  [Tomatillo Red Chili Salsa, [Fajita Vegetables...       11.25
2708                                                NaN        2.15
2717  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...       11.25
2833      [Fresh Tomato Salsa, [Rice, Cheese, Lettuce]]        8.75
2881                                                NaN        1.50
2973  [Tomatillo-Red Chili Salsa (Hot), [Rice, Black...        8.49
2977  [Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...        9.25
3121                                                NaN        4.45
3430                                                NaN        2.95
3637                         [Fresh Tomato Salsa, Rice]        8.75
3716                                       [Dr. Pepper]        1.09
3764  [Fresh Tomato Salsa, [Rice, Black Beans, Chees...        8.75
3829  [Fresh Tomato Salsa, [Rice, Cheese, Sour Cream...        8.75
3924                                                NaN        1.50
4112  [Fresh Tomato Salsa, [Fajita Vegetables, Rice,...       11.25
4155                                                NaN        4.45
4236                                       [White Rice]        8.50
4266                                                NaN        2.15
4372                                                NaN        4.45
4463                                         [Lemonade]        1.25
4479                                                NaN        1.50
4544                                                NaN        1.50
4570                                                NaN        1.50
4603                      [Tomatillo Green Chili Salsa]        9.25

DataFrame after handling duplicates:
      order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa
1            1         1                                   Izze
2            1         1                       Nantucket Nectar
3            1         1  Chips and Tomatillo-Green Chili Salsa
4            2         2                           Chicken Bowl
...        ...       ...                                    ...
4617      1833         1                          Steak Burrito
4618      1833         1                          Steak Burrito
4619      1834         1                     Chicken Salad Bowl
4620      1834         1                     Chicken Salad Bowl
4621      1834         1                     Chicken Salad Bowl

                                     choice_description  item_price
0                                                   NaN        2.39
1                                          [Clementine]        3.39
2                                               [Apple]        3.39
3                                                   NaN        2.39
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...       16.98
...                                                 ...         ...
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...       11.75
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...       11.75
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...       11.25
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...        8.75
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...        8.75

[4563 rows x 5 columns]

4. Quantity and Item Price:
Question: Examine the Quantity and Item Price columns. Are there any inconsistencies or anomalies that need correction?

In [ ]:
print(a['quantity'].describe())
print(a['item_price'].describe())

count    4563.000000
mean        1.076704
std         0.412739
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max        15.000000
Name: quantity, dtype: float64
count    4563.000000
mean        7.490083
std         4.244155
min         1.090000
25%         3.750000
50%         8.750000
75%         9.250000
max        44.250000
Name: item_price, dtype: float64

In [ ]:
negative_quantities = a[a['quantity'] < 0]
if not negative_quantities.empty:
    print("Rows with negative quantities:")
    print(negative_quantities)

In [ ]:
# Check for negative or zero item prices
non_positive_prices = a[a['item_price'] <= 0]
if not non_positive_prices.empty:
    print("\nRows with non-positive item prices:")
    print(non_positive_prices)

5. Choice Description:
Question: Analyze the Choice Description column. How should choices be handled, especially when there are multiple descriptions for a single item?

In [ ]:
a['choice_description'].unique()

array([nan, '[Clementine]', '[Apple]', ...,
       '[Roasted Chili Corn Salsa, [Pinto Beans, Sour Cream, Cheese, Lettuce, Guacamole]]',
       '[Tomatillo Green Chili Salsa, [Rice, Black Beans]]',
       '[Tomatillo Green Chili Salsa, [Rice, Fajita Vegetables, Black Beans, Guacamole]]'],
      dtype=object)

In [ ]:
unique_choices = a['choice_description'].unique()
choice_labels = {choice: label for choice, label in zip(unique_choices, ['a', 'b', 'c', 'd', 'e', 'f'])}

# Create a new column with labels
a['choice_label'] = a['choice_description'].map(choice_labels)

# Display the modified DataFrame with labels
print("\nDataFrame with Choice Labels:")
print(a[['item_name', 'choice_description', 'choice_label']].head())

DataFrame with Choice Labels:
                               item_name  \
0           Chips and Fresh Tomato Salsa
1                                   Izze
2                       Nantucket Nectar
3  Chips and Tomatillo-Green Chili Salsa
4                           Chicken Bowl

                                  choice_description choice_label
0                                                NaN            a
1                                       [Clementine]            b
2                                            [Apple]            c
3                                                NaN            a
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...            d

In [ ]:
print("Original DataFrame:")
print(a.head())

# Map unique choices to labels 'a' through 'f'
unique_choices = a['choice_description'].unique()
choice_labels = {choice: label for choice, label in zip(unique_choices, ['a', 'b', 'c', 'd', 'e', 'f'])}

# Create a new column with labels
a['choice_label'] = a['choice_description'].map(choice_labels)

# Drop the original 'choice_description' column
a = a.drop('choice_description', axis=1)

# Display the modified DataFrame with labels
print("\nDataFrame with Choice Labels:")
print(a.head())

Original DataFrame:
   order_id  quantity                              item_name  \
0         1         1           Chips and Fresh Tomato Salsa
1         1         1                                   Izze
2         1         1                       Nantucket Nectar
3         1         1  Chips and Tomatillo-Green Chili Salsa
4         2         2                           Chicken Bowl

                                  choice_description  item_price
0                                                NaN        2.39
1                                       [Clementine]        3.39
2                                            [Apple]        3.39
3                                                NaN        2.39
4  [Tomatillo-Red Chili Salsa (Hot), [Black Beans...       16.98

DataFrame with Choice Labels:
   order_id  quantity                              item_name  item_price  \
0         1         1           Chips and Fresh Tomato Salsa        2.39
1         1         1                                   Izze        3.39
2         1         1                       Nantucket Nectar        3.39
3         1         1  Chips and Tomatillo-Green Chili Salsa        2.39
4         2         2                           Chicken Bowl       16.98

  choice_label
0            a
1            b
2            c
3            a
4            d

In [ ]:
a

,order_id,quantity,item_name,item_price,choice_label
0,1,1,Chips and Fresh Tomato Salsa,$2.39,a
1,1,1,Izze,$3.39,b
2,1,1,Nantucket Nectar,$3.39,c
3,1,1,Chips and Tomatillo-Green Chili Salsa,$2.39,a
4,2,2,Chicken Bowl,$16.98,d
...,...,...,...,...,...
4617,1833,1,Steak Burrito,$11.75,NaN
4618,1833,1,Steak Burrito,$11.75,NaN
4619,1834,1,Chicken Salad Bowl,$11.25,NaN
4620,1834,1,Chicken Salad Bowl,$8.75,NaN
4621,1834,1,Chicken Salad Bowl,$8.75,NaN

In [ ]:
a

,order_id,quantity,item_name,choice_description,item_price,choice_label
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39,a
1,1,1,Izze,[Clementine],$3.39,b
2,1,1,Nantucket Nectar,[Apple],$3.39,c
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,a
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,d
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,NaN
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75,NaN
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,NaN
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,NaN
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,NaN

6. Handling Special Characters:
Question: Check for special characters in text-based columns (e.g., Item Name, Choice Description). How can these be addressed for consistency?


sol

we can Remove or replace special characters with appropriate alternatives. You can use the str.replace method in pandas with a regular expression to remove or replace specific characters.for choice_description we have alredayt replaced with lebels

In [ ]:
a['item_name'] = a['item_name'].str.replace(r'[^a-zA-Z0-9\s]', '')

<ipython-input-19-2521d7dfa143>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  a['item_name'] = a['item_name'].str.replace(r'[^a-zA-Z0-9\s]', '')

7. Order Id Integrity:
Question: Cross-reference the Order ID column for integrity. Are there any irregularities or patterns that need validation?

sol

We will check for any duplicate values in order id anf them remove them

In [ ]:
# Check for duplicate Order IDs
duplicate_orders = a[a.duplicated('order_id', keep=False)]
print("Duplicate Order IDs:")
print(duplicate_orders[['order_id', 'item_name']])

Duplicate Order IDs:
      order_id                             item_name
0            1          Chips and Fresh Tomato Salsa
1            1                                  Izze
2            1                      Nantucket Nectar
3            1  Chips and TomatilloGreen Chili Salsa
5            3                          Chicken Bowl
...        ...                                   ...
4617      1833                         Steak Burrito
4618      1833                         Steak Burrito
4619      1834                    Chicken Salad Bowl
4620      1834                    Chicken Salad Bowl
4621      1834                    Chicken Salad Bowl

[4428 rows x 2 columns]

In [ ]:
# Check the data type of Order ID
print("Data Type of Order ID:")
print(a['order_id'].dtype)

Data Type of Order ID:
int64

In [ ]:
print("Number of rows before removing duplicates:", len(a))

# Remove duplicate rows based on the 'Order ID' column, keeping the first occurrence
a = a.drop_duplicates(subset='order_id', keep='first')

# Display the number of rows after removing duplicates
print("Number of rows after removing duplicates:", len(a))

Number of rows before removing duplicates: 4563
Number of rows after removing duplicates: 1834

8. Item Name Standardization:
Question: Standardize the Item Name column. Are there variations that can be unified for better analysis?

solution

we can unify few of the name as follow:

In [ ]:
a['item_name'].unique()

array(['Chips and Fresh Tomato Salsa', 'Chicken Bowl', 'Steak Burrito',
       nan, 'Izze', 'Chicken Salad Bowl', 'Nantucket Nectar'],
      dtype=object)

In [ ]:
# Convert "Item Name" column to lowercase
a['item_name'] = a['item_name'].str.lower()

# Define variations and their standard names in a mapping dictionary
item_name_mapping = {
    'chips and fresh tomato salsa': 'Chips and Fresh Tomato Salsa',
    'izze': 'Izze',
    'nantucket nectar': 'Nantucket Nectar',
    'chips and tomatillo-green chili salsa': 'Chips and Tomatillo-Green Chili Salsa',
    'chicken bowl': 'Chicken Bowl',
    'steak burrito': 'Steak Burrito',
    'chicken salad bowl': 'Chicken Salad Bowl'
}

# Apply the mapping to standardize the "Item Name" column
a['item_name'] = a['item_name'].map(item_name_mapping)

# Display the DataFrame with standardized item names
print(a)

      order_id  quantity                     item_name  item_price  \
0            1         1  Chips and Fresh Tomato Salsa        2.39
4            2         2                  Chicken Bowl       16.98
5            3         1                  Chicken Bowl       10.98
7            4         1                 Steak Burrito       11.75
9            5         1                 Steak Burrito        9.25
...        ...       ...                           ...         ...
4610      1830         1                 Steak Burrito       11.75
4612      1831         1                           NaN        9.25
4615      1832         1                           NaN        8.75
4617      1833         1                 Steak Burrito       11.75
4619      1834         1            Chicken Salad Bowl       11.25

     choice_label
0               a
4               d
5               e
7               f
9             NaN
...           ...
4610          NaN
4612          NaN
4615          NaN
4617          NaN
4619          NaN

[1834 rows x 5 columns]

9. Quantity and Price Relationships:
Question: Investigate the relationships between Quantity and Item Price. Are there cases where adjustments need to be made for accurate +analysis?

In [ ]:
# Convert "Item Price" to numeric
a['item_price'] = a['item_price'].replace('[\$,]', '', regex=True).astype(float)

# Group by Quantity and calculate mean or median
quantity_price_stats = a.groupby('quantity')['item_price'].agg(['mean', 'median'])
print(quantity_price_stats)

# Calculate correlation coefficient
correlation_coefficient = a['quantity'].corr(a['item_price'])
print(f'Correlation Coefficient: {correlation_coefficient}')

# Linear regression analysis
if len(a['quantity'].unique()) > 1:
    slope = ((a['quantity']*a['item_price']).mean() - a['quantity'].mean()*a['item_price'].mean()) / ((a['quantity']**2).mean() - (a['quantity'].mean())**2)
    intercept = a['item_price'].mean() - slope * a['quantity'].mean()
    print(f'Linear Regression: y = {slope:.2f}x + {intercept:.2f}')
else:
    print('Insufficient data for linear regression analysis.')

               mean  median
quantity
1          9.092804    8.99
2         16.606842   17.50
3         21.390000   26.07
4         19.680000   19.68
5          7.500000    7.50
8         13.520000   13.52
15        44.250000   44.25
Correlation Coefficient: 0.4868381407447502
Linear Regression: y = 3.74x + 5.58


10. Data Integrity Check:
Question: Perform a data integrity check by ensuring that quantities and prices align with the corresponding items and descriptions.

In [ ]:
# Convert "Item Price" to numeric
a['item_price'] = a['item_price'].replace('[\$,]', '', regex=True).astype(float)

# Check if 'choice_description' column exists in the DataFrame
if 'choice_description' in a.columns:
    # Group by 'item_name' and 'choice_description' and check for inconsistencies
    grouped_data = a.groupby(['item_name', 'choice_description'])[['quantity', 'item_price']].agg(['sum', 'mean'])
else:
    # Group only by 'item_name' and check for inconsistencies
    grouped_data = a.groupby(['item_name'])[['quantity', 'item_price']].agg(['sum', 'mean'])

# Check for quantity inconsistencies
quantity_inconsistencies = grouped_data[grouped_data[('quantity', 'sum')] != grouped_data[('quantity', 'mean')]]
print("Quantity Inconsistencies:")
print(quantity_inconsistencies)

# Check for price inconsistencies
price_inconsistencies = grouped_data[grouped_data[('item_price', 'sum')] != grouped_data[('item_price', 'mean')]]
print("\nPrice Inconsistencies:")
print(price_inconsistencies)

Quantity Inconsistencies:
                             quantity           item_price
                                  sum      mean        sum       mean
item_name
Chicken Bowl                      501  1.070513    4838.83  10.339380
Chicken Salad Bowl                 72  1.220339     745.00  12.627119
Chips and Fresh Tomato Salsa       19  3.800000      54.93  10.986000
Nantucket Nectar                    6  1.200000      20.34   4.068000
Steak Burrito                     246  1.046809    2464.16  10.485787

Price Inconsistencies:
                             quantity           item_price
                                  sum      mean        sum       mean
item_name
Chicken Bowl                      501  1.070513    4838.83  10.339380
Chicken Salad Bowl                 72  1.220339     745.00  12.627119
Chips and Fresh Tomato Salsa       19  3.800000      54.93  10.986000
Nantucket Nectar                    6  1.200000      20.34   4.068000
Steak Burrito                     246  1.046809    2464.16  10.485787

11. Converting to CSV:
Optional Question: If needed, convert the cleaned dataset to a CSV file using the to_csv function with sep=','

In [ ]:
# Save the cleaned dataset to a CSV file
a.to_csv('cleaned_dataset.csv', sep=',', index=False)

12. Handling Categorical Data:
Question: For categorical columns (e.g., Item Name), consider encoding or transforming them into a format suitable for analysis.

In [ ]:

from sklearn.preprocessing import LabelEncoder

# Initialize the LabelEncoder
label_encoder = LabelEncoder()

# Encode the "Item Name" column
a['item_name_encoded'] = label_encoder.fit_transform(a['item_name'])

# Display the DataFrame with the encoded "Item Name"
print(a[['item_name', 'item_name_encoded']].drop_duplicates())

                         item_name  item_name_encoded
0     Chips and Fresh Tomato Salsa                  2
4                     Chicken Bowl                  0
7                    Steak Burrito                  5
11                             NaN                  6
66                            Izze                  3
135             Chicken Salad Bowl                  1
1626              Nantucket Nectar                  4

13. Consistent Quantity and Price Units:
Question: Ensure consistency in units for Quantity and Item Price. Should any conversions or adjustments be made for uniform analysis?

In [ ]:
# Convert "Item Price" to numeric
a['item_price'] = a['item_price'].replace('[\$,]', '', regex=True).astype(float)

# Check unique units for Quantity
unique_quantity_units = a['quantity'].unique()
print("Unique Quantity Units:", unique_quantity_units)

# Check unique units for Item Price
unique_price_units = a['item_price'].apply(lambda x: str(x)[-1]).unique()
print("Unique Item Price Units:", unique_price_units)

Unique Quantity Units: [ 1  2  3  4  5 15  8]
Unique Item Price Units: ['9' '8' '5' '6' '4' '2' '3' '0' '7']